### ISSUE TITLE
Sources for flow traversal algorithm

### ISSUE THREAD

**Issue by bhaugen** [valueflows/vf-apps-traversing-the-flows#1]
This [vocabulator issue](https://github.com/valueflows/django-vocabulator/issues/7) was written up while refactoring and simplifying the traversal code in NRP. Given the vocabutor code, probably no reason to look deeply into the NRP code.

[Bipartite graphs](https://github.com/ipfs/notes/issues/168) ... [visualized](https://github.com/statebox/tbpt-viewer). I think value flow graphs are tripartite (processes, transfers, and the resource flows between them) but if you consider both the processes and transfers to be nodes, and the resource flows to be edges, it becomes bipartite.

Graph traversal algorithms: many sources, [here's one](https://eli.thegreenplace.net/2015/directed-graph-traversal-orderings-and-applications-to-data-flow-analysis/).

Petri nets: also lots of sources, [here's one](http://cpntools.org/).

[Material flow analysis](https://en.wikipedia.org/wiki/Material_flow_analysis)

[Dependent demand](https://www.valueflo.ws/appendix/dependent-demand.html)

John Baez's [Applied Category Theory class](https://forum.azimuthproject.org/discussion/1717/welcome-to-the-applied-category-theory-course). Especially [chapter 2 in the textbook about resource theories](https://forum.azimuthproject.org/discussion/2073/chapter-2).

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-apps-traversing-the-flows/-/issues/1.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
