### ISSUE TITLE
How to spec an algorithm in a paradigm-independent way

### ISSUE THREAD

**Issue by bhaugen** [valueflows/vf-apps-traversing-the-flows#2]
By "paradigm", I mean object-oriented, procedural, or functional.

For example, here is fairly minimal python code to traverse inflow from a resource to all the flows that went into that resource, using a depth-first search:
```
def resource_inflows(resource):
    visited = set()
    flows = [resource,]
    inflows_dfs(resource, flows, visited)
    return flows
    
def inflows_dfs(element, flows, visited):
    visited.add(element)
    preds = element.preds()
    for pred in preds:
        if pred not in visited:
            flows.append(pred)
            inflows_dfs(pred, flows, visited)
```
These are procedural functions, but they depend on each element being able to respond to element.preds().

Which I think assumes that each element is an object, and preds() is a method of that object.

How would this be written in a functional-programming style?

And can some pseudo-code be written that would work for either style?

**Comment by bhaugen** [comment]
> And can some pseudo-code be written that would work for either style?

Advice from @nanomonkey in scuttlebutt:
> specify the data and protocol only and allow each implementer to worry about implementation details, as each style will deal with the data differently. Perhaps provide testing code, such as an API that gives out test data and asserts that the correct response is given.

**Comment by bhaugen** [comment]
For this app, I will follow nanomonkey's advice, but [the Vocabulator](http://valueflows.pythonanywhere.com/) cannot yet show the data for the flows (altho it can diagram them).

So the first thing to do for this app is to get the Vocabulator to show the data.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-apps-traversing-the-flows/-/issues/2.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
