### ISSUE TITLE
traversal for Holo Demo Scenario

### ISSUE THREAD

**Issue by bhaugen** [valueflows/vf-apps-traversing-the-flows#3]
As specified in https://github.com/valueflows/valueflows/issues/385

End resources that might be traced backwards to see where they came from, aka their provenance:
* Al's Coffee (not interesting, coffee beans came from an adjustment)
* Bea's Apple turnover
* Cloe's Coffee

**Bea's Apple turnover**

* EconomicResource: id: 60, resourceClassifiedAs: Apple turnover
    * received from EconomicEvent: id: 61, action: receive, provider: Cloe, receiver: Bea, affects: EconomicResource 60
        * outputOf: Transfer 5
            * EconomicEvent: id: 60, action: give, provider: Cloe, receiver: Bea, affects: EconomicResource 55 (currentQuantity now 0), inputOf: Transfer 5
               *  EconomicResource 55, resourceClassifiedAs: Apple turnover
                   * EconomicEvent: id: 51, action: produce,  outputOf: Process 789,  affects: EconomicResource 55
                       * Process: id: 789, name: Bake turnover
                           * EconomicEvent: id: 50,  action: consume, inputOf: Process 789,  affects: EconomicResource 30 (currentQuantity now 0)
                               * EconomicEvent: id: 31, action: receive, provider: Al, receiver: Cloe, affects: EconomicResource 30, outputOf: Transfer 2
                                   * Transfer: id: 2
                                       * EconomicEvent: id: 30, action: give, provider: Al, receiver: Cloe, affects: EconomicResource 1 (currentQuantity now 97), inputOf: Transfer 2
                                           * EconomicResource: id: 30, resourceClassifiedAs: Apple
                                               * Process: id: 123, name: Pick apples
                                                   * EconomicEvent: id: 1, action: produce, outputOf: Process 123, affects: EconomicResource 1    

_(Note: github markdown apparently stops indenting at some point (after Transfer 2), or I did something wrong...)_

**Comment by bhaugen** [comment]
About the traversal algorithm:

In general, each element should be able to answer its inputs and outputs, or what comes before or after in a traversal.

* For an EconomicResource:
    * after: EconomicEvents that are inputs to Processes or Transfers
    * before: EconomicEvents that are outputs from Processes or Transfers
* For a Process or Transfer:
    * after: EconomicEvents that are outputs
    * before: EconomicEvents that are inputs
* For an EconomicEvent:
    * after: 
        * a Process or Transfer to which it is an input, or
        * an EconomicResource which it incremented
    * before: 
        * a Process or Transfer from which is is an output, or
        * if it is an input to a Process or Transfer, the EconomicResource which it affects.

**Comment by bhaugen** [comment]
See also https://github.com/valueflows/valueflows/issues/349

That issue seems to be closed now, I suspect prematurely, but the rules will affect traversals. For example, the algorithm notes above do not deal correctly with resources which have the same identity before and after a process: for example, bike repair. It's the same bike, but maybe with some new parts. So if you are traversing from the resource, "before" could be an output from a process that changed the resource, while "after" could be an input to a process that changed the resource.

@fosterlynn @elf-pavlik how does VF currently specify such processes and events?

**Comment by fosterlynn** [comment]
>how does VF currently specify such processes and events?

We have actions `accept` and `improve` for that scenario.  We don't have `stage` or similar defined explicitly.  Maybe documenting all the transversal logic will help us define what else is needed.

Also, feel free to re-open any issues you think warrant it.

**Comment by elf-pavlik** [comment]
Great move @bhaugen I think we should start documenting more algorithms. I believe that this algorithm should treat *give* and *receive* the same way as *load* and *unload*, possibly after addressing *TODO* in https://github.com/valueflows/valueflows/pull/386

**Comment by bhaugen** [comment]
More related issues:
* https://github.com/valueflows/django-vocabulator/issues/7
* https://github.com/valueflows/vf-apps-traversing-the-flows/issues/1
* https://github.com/valueflows/vf-apps-traversing-the-flows/issues/2

**Comment by bhaugen** [comment]
Another algorithm note: traversals require recursion, as you can see in the code referenced in https://github.com/valueflows/django-vocabulator/issues/7

I think it would be possible to do it as a one-liner using comprehensions in a sufficiently powerful functional programming language, altho I am not a sufficiently powerful functional programmer to prove it yet, and it might require some changes to the algorithm notes above.

Traversals will also need to guard against cycles, which I do with a set called visited as you can see here:
https://github.com/valueflows/django-vocabulator/blob/master/vocab/models.py#L327

And then you can follow its use here: https://github.com/valueflows/django-vocabulator/blob/master/vocab/models.py#L207

**Comment by fosterlynn** [comment]
It seems like at a minimum, EconomicResource, Process, Transfer, and EconomicEvent need methods for `previous` and `next` or whatever the best terms are.  If that would be part of the vocabulary, it would certainly facilitate reporting value flows across instances.

**Comment by bhaugen** [comment]
Another angle on traversals is access to data. Who can traverse from one hop to another? 

Holochain's explicitly agent-centric environment should be good for thinking about this. Each agent has a source chain, and then there's a DHT (distributed hash table) which is public info (within some limits).

Wim Laurier has thought a lot about this.
![collaboration space transfer model](https://user-images.githubusercontent.com/117439/50654080-47a0d100-0f51-11e9-82cc-d7e9af36fe72.png)

In Holochain, I think his Transfer would live in the DHT (which would be Wim's "collaboration space"), while his \<<give\>> and \<<take\>> might live in the source chains of the providing and receiving agents.

There are some other complications in that scenario dealing with doubly-signed transactions, which I think we want to both Holochain and ActivityPub, but I'll pass on them for now.

**Comment by bhaugen** [comment]
@elf-pavlik 
>  I believe that this algorithm should treat give and receive the same way as load and unload, possibly after addressing TODO in valueflows/valueflows#386

I will work on a similar treatment for transportation in an exchange. One big diff between give and receive vs load and unload is that transportation is a process and the loaded resources become part of the inventory of the transportation vehicle, where they live for the duration of their ride.

Give and take happen in the best case in a very short time. All that is happening is transferring rights and responsibilities to resources. 

People do shortcut transfers to include a change of location of the resource, but that is what Bill McCarthy calls an implementation compromise. You know that all this other stuff is happening but you don't think it is worth recording. In a fully-detailed implementation, transfers do not change the location of the resource. that requires a process.

LIkewise in a transportation process, \<<load\>> also is an implementation compromise. It puts the resources onto the transportation vehicle, but it also transfers responsibility to the transportation agent, which usually has some agreements with some fine print about what happens if something bad happens to the resources.

And ownership usually gets transferred at the FOB point, altho an explicit \<<take\>> would only happen if it was FOB destination and the transporter had the receiving agent sign for the resources.

**Comment by elf-pavlik** [comment]
@bhaugen I've written some snippets with various transportation scenarios in https://github.com/valueflows/valueflows/pull/386

**Comment by bhaugen** [comment]
@elf-pavlik I have all of those up in tabs and am studying.

**Comment by bhaugen** [comment]
@elf-pavlik first draft of [a complicated transportation scenario](https://github.com/valueflows/vf-apps-traversing-the-flows/issues/4)

I did it as an issue so we can all comment and improve before documenting it more permanently.

**Comment by sqykly** [comment]
> 
> 
> It seems like at a minimum, EconomicResource, Process, Transfer, and EconomicEvent need methods for `previous` and `next` or whatever the best terms are. If that would be part of the vocabulary, it would certainly facilitate reporting value flows across instances.

I've been using `trace` and `track`.  HoloREA already has it for Events and Transfers, Processes coming tonight, Resources when I see a good opportunity.

**Comment by fosterlynn** [comment]
>I've been using trace and track.

:+1:  to "trace" and "track".

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-apps-traversing-the-flows/-/issues/3.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
