### ISSUE TITLE
A complicated transportation flow

### ISSUE THREAD

**Issue by bhaugen** [valueflows/vf-apps-traversing-the-flows#4]
This is the most complicated transporation flow I could come up with as of now. Will add more complications as I think of them.

You would never want to take all of the steps in this scenario. When I get finished, I will do another scenario with what I think is the bare minimum.

I will assume a tightly controlled environment, where inventory is kept in locked storage. 

* This flow would start with a transfer of goods from storage to shipping dock: a transfer of custody from the stock-keeping agent to the shipping agent.
  * This transfer would decrement storage inventory and increment shipping dock inventory.
* Next, either shipping dock workers or transportation vehicle workers would load the goods onto the transportation vehicle.  This is a load event on a new process for the transportation.
  * At the same time, a transfer would change custody of the goods from the shipping dock agent to the transportation agent.
    * The rights and responsibilities for custody of goods in shipment would probably be documented in fine print on the back of the shipping label...
   * This transfer would decrement shipping dock inventory and increment transportation vehicle inventory, also called [Cargo Manifest](https://github.com/valueflows/valueflows/blob/master/use-cases/cargo-manifest.md).
   * Either providing or receiving agent would also add the goods to their Goods in Transit inventory.
     * From https://www.accountingtools.com/articles/what-are-goods-in-transit.html  
   
>   * Goods in transit refers to merchandise and other types of inventory that have left the shipping dock of the seller, but not yet reached the receiving dock of the buyer. The concept is used to indicate whether the buyer or seller of goods has taken possession, and who is paying for transport. Ideally, either the seller or the buyer should record goods in transit in its accounting records. The rule for doing so is based on the shipping terms associated with the goods, which are:
>         * FOB shipping point. If the shipment is designated as freight on board (FOB) shipping point, ownership transfers to the buyer as soon as the shipment departs the seller.
>         * FOB destination. If the shipment is designated as freight on board (FOB) destination, ownership transfers to the buyer as soon as the shipment arrives at the buyer.

   * Also, a transfer would change ownership of the goods from seller to buyer at the FOB point.
* At the destination, either transportation vehicle workers or shipping dock workers would unload the goods from the transportation vehicle.  This is an unload event on the transportation process.
  * Then a transfer would change custody from the transportation vehicle to the receiving doc.
  * At the same time, goods-in-transit would be decremented (for whichever agent was responsible for tracking goods in transit).
  * The transportation agent would log a transportation service event where the provider would be the transportation agent and the receiver would be whichever agent was responsible for paying for shipping.
  * And finally, another transfer would change custody from the receiving dock to storage inventory.

**Comment by bhaugen** [comment]
That scenario did not deal with the reciprocal flows of paying for goods and transportation service.

**Comment by elf-pavlik** [comment]
> This event would decrement shipping dock inventory and increment transportation vehicle inventory, also called Cargo Manifest.

Currently one event only affects one resource. You could decrement dock with *load* and then increment on vehicle resource with *receive* or just *increment*.

> Also, a transfer event would transfer ownership of the goods from seller to buyer at the FOB point.

Currently VF doesn't have *transfer* action which event could use. At the same time any event (no matter which action it uses) can have *provider* and *receiver* specified. So this could happen on *load* (~ FOB shipping point), *unload* (~ FOB destination) or any other event they find fit.
Also VF currently doesn't provide any way to specify change of *ownership* or *possesion*  or *custody* or something else. 


If you take a look at *shipping packaged* variant in my PR https://github.com/valueflows/valueflows/pull/386/files#diff-ec6dd08b70d0091f4002433eceb7303eR286 you can see something very close to what you described here. I think current use of *provider* and *receiver* seems to imply change of *possession*. As I mentioned in previous paragraph at current stage we have no way to specify which rights get 'transferred'.

**Comment by bhaugen** [comment]
@elf-pavlik I was sloppy and wrote "transfer event" in a couple of places in that scenario. I think I changed them all, and now they are just transfers.

> VF currently doesn't provide any way to specify change of ownership or possesion or custody or something else.

https://www.valueflo.ws/introduction/exchanges.html
> Transfers do not create or change or transport an economic resource, they just put the rights and responsibilities for a resource into a different agent's hands so that the resource can be used or consumed or transferred again.

So, help me out. How else would I change that scenario to express changes of custody or ownership?

It is necessary to do so, often, in this and many other scenarios. I don't think VF needs to specify the rights in detail. Both custody and ownership are generally understood and can be specified in more detail in an implementation if needed.

It is also often necessary to change the location of a resource without changing custody or ownership. 

For example, our neighbor works in an automated warehouse where a robot changes locations of resources and keeps track of where they are, but most of them arel owned by a cooperative and in the custody of its warehouse management sub-organization. 

That cooperative also distributes goods for other cooperatives, which sometimes end up in the same warehouse. Those are owned by some other organization, but in the custody of the warehouse management sub-organization.

**Comment by bhaugen** [comment]
Here's how Sensorica specifies rights and responsibilities for resources. They have a set of community-defined Agent Resource Roles: roles that Agents play in relation to Resources.
![sensorica agentresourceroles](https://user-images.githubusercontent.com/117439/50735041-c1150b00-116d-11e9-9261-6e509dbfa0a0.png)

Each of the roles has a description. Here's the description for Custodian:
> A custodian of a resource is an affiliate, or a group of affiliates that are trusted by the community to manage a resource, and to grant access to other affiliates according to certain rules 

That description could be more elaborate: could specify some rules, etc. But the actual rules are specified by the custodian of a particular resource in other documents.

**Comment by elf-pavlik** [comment]
Since conversation moves in direction of discussing more general requirement, I've responded to it in https://github.com/valueflows/valueflows/issues/148#issuecomment-451759962

> It is also often necessary to change the location of a resource without changing custody or ownership.

The 'relocation' variants in https://github.com/valueflows/valueflows/pull/386/files build on that scenario.
The last snippet for 'shipping / relocation - concurrent' might involve change of custody/possession during transportation but doesn't involve any change of ownership.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-apps-traversing-the-flows/-/issues/4.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
