### ISSUE TITLE
Potential resource flows

### ISSUE THREAD

**Issue by bhaugen** [valueflows/vf-apps-traversing-the-flows#5]
If you know some Agents' intended inputs and intended outputs by Resource Classification or even better Resource Specification, you can figure out the potential resource flows between those Agents. 

Potential resource flows can be useful in analyzing the economic potentials in a community or bioregion.

You can figure out the gaps (where resources are needed but not produced in the community, and thus must be imported from outside (which in a money economy exports money from the community)). And the resources that are produced but not needed in the community and thus must be exported (which in a money economy brings in new money).

This kind of analysis would most likely use [ValueFlows Scenarios](https://valueflo.ws/introduction/estimates.html).

We have done this before in [Locecon](http://locecon.org/), an experimental economic modeling and analysis app. Locecon was developed before ValueFlows, and uses basically the same REA-based model, but has some different names.

You can figure out potential resource flows by Agent, or by group of Agents, or what Locecon calls Functions, where a Function is some activity performed by agents that inputs and outputs Resources, like Farming or Baking. One Agent might perform more than one Function, and many Agents might perform the same Function. In VF Scenarios, Functions would be high-level Process Classifications or Specifications.

For the remainder of this writeup, I will use the Locecon Function name, and link to some Locecon examples.

Locecon diagrams the potential resource flows and does some simple analytical reports.

You can see all of these aspects in this Locecon cluster: http://locecon.org/clusters/network/27/qty/fn/ 

Here are several other public clusters: http://locecon.org/clusters/

And here is how some of the analytical possibilities were used in Nova Scotia fisheries: http://locecon.org/nova-story/

### Potential Resource flow diagrams

The nodes in the diagram can be individual Agents or aggregations of Agents, or they can be Functions (VF Scenario high-level Process Specifications).

Edges appear where one node's intended output Resource Classification or Specification _(but one diagram should settle on one or the other)_ matches the intended input Resource Classification or Specification of another node. 

If you have quantities, the width of the arrows on the diagram can depend on the quantity of the flow. That makes it into a [Sankey diagram](https://en.wikipedia.org/wiki/Sankey_diagram).

If you want gory details, I can point to and also explain some old sloppy code. Just ask.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-apps-traversing-the-flows/-/issues/5.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
